### ISSUE TITLE
Min date and max date not working

### ISSUE THREAD

**Issue by ev243** [mugifly/jquery-simple-datetimepicker#140] opened 2014-11-10 13:41 UTC
On your demo site, the min and max date on the date range is not working.

So if I choose 24 Nov 2014 for the start, I can still choose dates from the past (i.e. 23 Nov 2014).

**Comment by royzrj** [comment] 2015-10-27 12:34
@ev243 @naga2raja is this still happening?

**Comment by naga2raja** [comment] 2015-10-28 14:46
Hey @royzrj ,

Yes, the issue is still happening. Please see the demo site http://mugifly.github.io/jquery-simple-datetimepicker/jquery.simple-dtpicker.html under "Date Ranges".

**Comment by royzrj** [comment] 2015-10-28 15:59
@naga2raja sorry, should've made myself clear
Is the issue still happening using the code from master branch?
As I can't reproduce this bug as of now, using the master branch code.

FYI: I just accessed the demo and, yes, it happens there, but only because it is not using the master branch code. There is a new "Date Ranges" section, which uses the setMinDate and setMaxDate functions, which I think are best suited for the job than calling appendDtpicker several times.

**Comment by naga2raja** [comment] 2015-10-30 12:56
@royzrj  I'm sorry, I didn't check it out with latest master branch.

Will check it and let you know.

**Comment by royzrj** [comment] 2015-11-04 15:36
Fixed on master branch, as informed on #144

**Closed** 2015-11-06 16:27 UTC
Labels: bug
